# Generated by Django 3.2.9 on 2021-11-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField()),
                ('info_adicional', models.CharField(max_length=300, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-fecha_lectura',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=30)),
                ('latitud', models.BigIntegerField(blank=True, null=True)),
                ('longitud', models.BigIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidad_de_medida', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AntartidaFront.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.lectura')),
                ('tipo_medicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AntartidaFront.tipomedicion')),
            ],
        ),
        migrations.AddField(
            model_name='lectura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.sensor'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evento', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_evento', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.sensor')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.tipoevento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.usuario')),
            ],
            options={
                'ordering': ('-fecha_evento',),
            },
        ),
    ]
