# Generated by Django 3.2.9 on 2021-11-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLectura', models.DateTimeField()),
                ('infoAdicional', models.CharField(max_length=300, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-fechaLectura',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSensor', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidadDeMedida', models.CharField(max_length=30)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=300)),
                ('deleted', models.BooleanField(default=False)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.lectura')),
                ('tipoMedicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AntartidaFront.tipomedicion')),
            ],
        ),
        migrations.AddField(
            model_name='lectura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.sensor'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloEvento', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('fechaEvento', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.sensor')),
                ('tipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.tipoevento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AntartidaFront.usuario')),
            ],
            options={
                'ordering': ('-fechaEvento',),
            },
        ),
    ]
