# Generated by Django 3.2.9 on 2021-11-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntartidaFront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitud',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitud',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
