# Generated by Django 3.1.7 on 2021-11-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AntartidaFront', '0003_auto_20211122_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ('-fecha',)},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_evento',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='tipo_evento',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='titulo_evento',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombre_rol',
            new_name='nombre',
        ),
    ]
