# Generated by Django 3.1.7 on 2021-11-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AntartidaFront', '0004_auto_20211123_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ('-fecha_evento',)},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fecha_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='tipo',
            new_name='tipo_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='titulo_evento',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='nombre_rol',
        ),
    ]
