# Generated by Django 3.1.7 on 2021-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntartidaFront', '0005_auto_20211123_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomedicion',
            name='color',
            field=models.CharField(default='rgba(255, 99, 132, 0.5)', max_length=50),
        ),
    ]
